set_property PACKAGE_PIN Y18 [get_ports clk_100MHz]
set_property PACKAGE_PIN E1 [get_ports TMDS_Tx_Clk_P]
set_property PACKAGE_PIN G1 [get_ports {TMDS_Tx_Data_P[0]}]
set_property PACKAGE_PIN H2 [get_ports {TMDS_Tx_Data_P[1]}]
set_property PACKAGE_PIN K1 [get_ports {TMDS_Tx_Data_P[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk_100MHz]

set_property PACKAGE_PIN M13 [get_ports {key[0]}]
set_property PACKAGE_PIN K14 [get_ports {key[1]}]
set_property PACKAGE_PIN K13 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {key[0]}]
